spring:
  application:
    name: service-registry
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}"
    register-with-eureka: false
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10